steps:
  - name: 'golang:1.15-buster'
    entrypoint: 'go'
    args: ['build', '.']
  - name: 'gcr.io/kaniko-project/executor:v1.3.0'
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/hochikisu:$TAG_NAME-alpine
      - --cache=true
      - --cache-ttl=6h